#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_HTML
---
excerpt: Describe the principles in detail. And how to blog with emacs jekyll and github page.
layout: post
category : howto
tags : [jekyll, tutorial, github]
---
#+END_HTML

* About This Article

* The Basic Principles
** What is Jekyll and static site
Static Site, as it's name, is delivered to the user exactly as stored. The dynamic part of the page, like comment, must be add as plugins. The advantage is that it's cheap and fast to develop, and easy to host. With generators like Jekyll, you can build a site in seconds.
** What is github pages
GitHub Pages are public webpages freely hosted and easily published through github. There are two ways to set up a github page.
First, You can create a  repository called "username.github.io", where username is your username for github. Then this repository is your default git page repo. Push your site to master branch of this repo. You will see the site at https://username.github.io/ . 
Second, actually, every repository can be a git hub page by creating a branch called gh-pages. All the content on this branch, can be visit via https://username.github.io/project. For example, my blog repository https://github.com/terrylu87/blog . I create gh-pages branch on it. So that you can visit my site by  https://terrylu87.github.io/blog.
** The Emacs and org-mode

* Why Emacs-Jekyll-GithubPages
I use Emacs org-mode to write the blog. The org-mode provide a perfect way to compose logical orient articales.
* How to set up the blog
** Set up your github pages
This whouldn't be a problem if you understand the basic principle describe in previous section. For me, I prefer the gh-pages branch.
#+BEGIN_SRC bash
git clone https://username.github.io/project.git blog
cd blog
git checkout -b gh-pages
#+END_SRC
** Generate the static site
There are many tutorials online about how to generate a static blog. The document on the Jekyll official website is good. But if you want a customized theme, or support the archive and tags and other feature. You need a better starting point. I use Jekyll Bootstrap : http://jekyllbootstrap.com/. The Jekyll Bootstrap support theme, which can eassily be installed and changed.
#+BEGIN_SRC bash
git clone https://github.com/plusjade/jekyll-bootstrap.git jb
#+END_SRC
** Test your site.
Install ruby and javascript enviroment
#+BEGIN_SRC bash
sudo apt-get install nodejs ruby-dev
#+END_SRC
Install Jekyll
#+BEGIN_SRC bash
sudo gem install jekyll
#+END_SRC
Test the site
#+BEGIN_SRC bash
cd blog
jekyll serve
#+END_SRC
** Push your site to github
#+BEGIN_SRC bash
cd blog/
cp -rf jb/* .
git commit
git push origin gh-pages
#+END_SRC
* Other interesting stuff
** Comments
I use disqus for comment. Regisrate an accont at disqus official site. They will provide some tutorials. But since our jekyll bootstrap had disqus integration. We just need change the \_config.yml file under jekyll root dir.
#+BEGIN_SRC css  
comments :
    provider : disqus
    disqus :
      short_name : your_short_name
#+END_SRC
** Theme and decoration
You can find a theme at http://themes.jekyllbootstrap.com/
#+BEGIN_SRC bash
cd blog/
rake theme:install git="https://github.com/jekyllbootstrap/theme-the-program.git"
rake theme:install name="THEME-NAME"
#+END_SRC
* Todo
** add search function