#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+BEGIN_HTML
---
excerpt: 
layout: post
category : HTML5
tags : [javascript]
---
#+END_HTML

Ways to clear an existing array A. (From Stack Overflow)

* Method 1
(this was my original answer to the question)
#+begin_src javascript
A = [];
#+end_src
This code will set the variable A to a new empty array. This is perfect if you don't have references to the original array A anywhere else because this actually creates a brand new (empty) array. You should be careful with this method because if you have referenced this array from another variable or property, the original array will remain unchanged. Only use this if you only reference the array by its original variable A.

This is also the fastest solution.

* Method 2 (as suggested by Matthew Crumley)
#+begin_src javascript
A.length = 0
#+end_src
This will clear the existing array by setting its length to 0. Some have argued that this may not work in all implementations of Javascript but it turns out that this is not the case. It also works when using "strict mode" in Ecmascript 5 because the length property of an array is a read/write property.

* Method 3 (as suggested by Anthony)
#+begin_src javascript
A.splice(0,A.length)
#+end_src
Using .splice() will work perfectly, but it's not very efficient because the .splice() function will return an array with all the removed items, so it will actually return a copy of the original array.

* Method 4 (as suggested by tanguy_k)
#+begin_src javascript
while(A.length > 0) {
    A.pop();
}
#+end_src
This solution is not very succinct but it is by far the fastest solution (apart from setting the array to a new array). If you care about performance, consider using this method to clear an array. Benchmarks show that this is at least 10 times faster than setting the length to 0 or using splice().